[template]
src = "server.properties.tmpl"
dest = "/kafka/config/server.properties"
keys = [
  "/self/container/service_index",
  "/self/host/agent_ip",
  "/self/stack/services/zookeeper/containers",
]
reload_cmd = "pkill java"
