[template]
src = "create-server.properties.sh.tmpl"
dest = "/create-server.properties.sh"
keys = [
  "/self/container/service_index",
  "/self/host/agent_ip",
  "/self/stack/services/zookeeper/containers",
]
reload_cmd = "sh /create-server.properties.sh && pkill java"
